### PR TITLE
Fixes #13 - AppIsConfigured to AppIfConfigured 

### LINKED ISSUE #13: xcaddy build failed ctx.AppIsConfigured undefined
Tried to build xcaddy with modcaddy 

`xcaddy build --with github.com/gaukas/clienthellod/modcaddy`

Got this:

```
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.5
go: downloading cloud.google.com/go/compute v1.20.1
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
2023/10/02 20:58:39 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /root/4/caddy -ldflags -w -s -trimpath
# github.com/gaukas/clienthellod/modcaddy/listener
/root/.go/pkg/mod/github.com/gaukas/clienthellod@v0.4.0/modcaddy/listener/listener.go:65:10: ctx.AppIsConfigured undefined (type caddy.Context has no field or method AppIsConfigured)
# github.com/gaukas/clienthellod/modcaddy/handler
/root/.go/pkg/mod/github.com/gaukas/clienthellod@v0.4.0/modcaddy/handler/handler.go:53:10: ctx.AppIsConfigured undefined (type caddy.Context has no field or method AppIsConfigured)
2023/10/02 20:58:40 [INFO] Cleaning up temporary folder: /tmp/buildenv_2023-10-02-2058.860729220
2023/10/02 20:58:40 [FATAL] exit status 1
```

What can be wrong?

### PR DESCRIPTION
**Pull request by cowsay**
Also encountered this error so i changed to nil check instead of bool
```# github.com/gaukas/clienthellod/modcaddy/listener
/root/4/clienthellod/modcaddy/listener/listener.go:65:6: invalid operation: operator ! not defined on ctx.AppIfConfigured(app.CaddyAppID) (value of type any)
# github.com/gaukas/clienthellod/modcaddy/handler
/root/4/clienthellod/modcaddy/handler/handler.go:53:6: invalid operation: operator ! not defined on ctx.AppIfConfigured(app.CaddyAppID) (value of type any)```

### CODE REVIEW

**Comment by cowsay** [comment]
Fixes #13

**Comment by gaukas** [comment]
It might be better if you'd love to update the dependencies in go.mod (I guess that's why to Go build has failed). Or I can do that if it is inconvenient for you.

**Comment by gaukas** [comment]
And I'd suggest just combine the `App()` call with `AppIfConfigured()`: 

```go
if app := AppIfConfigured(...); app == nil {
    // ...
} else {
    // ...
}
```

Since it is returning the `App` if it is configured.

**Comment by gaukas** [comment]
Oof. Seems like the latest Caddy does not support Go 1.20 am I right? Or something else happened.

**Comment by gaukas** [comment]
I see. Updating transitive dependencies breaks caddy. Bummer. People love breaking changes without new major version.

**Comment by gaukas** [comment]
Huzzah.

**Pull request merged**
